#!/usr/bin/env python3
"""
AI Melli — Text Generator
"""

import urllib.request
import json
import sys
import os
import time


def generate_text(prompt, model="openai", temperature=0.8, system_message=None):
    if not system_message:
        system_message = "You are a creative and helpful AI assistant. Write detailed, well-structured, and engaging content. Use markdown formatting when appropriate."

    payload = json.dumps({
        "messages": [
            {"role": "system", "content": system_message},
            {"role": "user", "content": prompt}
        ],
        "model": model,
        "temperature": temperature
    }).encode("utf-8")

    url = "https://text.pollinations.ai/"
    req = urllib.request.Request(url, data=payload, method="POST")
    req.add_header("Content-Type", "application/json")
    req.add_header("User-Agent", "AI-Melli/1.0")

    print(f"Sending request to {url}...")
    print(f"Model: {model}, Temperature: {temperature}")

    with urllib.request.urlopen(req, timeout=120) as resp:
        raw = resp.read().decode("utf-8")

    # Try parse as JSON
    try:
        parsed = json.loads(raw)
        if isinstance(parsed, dict):
            text = parsed.get("choices", [{}])[0].get("message", {}).get("content", "")
            if not text:
                text = parsed.get("content", "")
            if not text:
                text = json.dumps(parsed, ensure_ascii=False)
        else:
            text = str(parsed)
    except (json.JSONDecodeError, IndexError, KeyError):
        text = raw

    return text


def main():
    config_path = sys.argv[1] if len(sys.argv) > 1 else "/tmp/ai_melli_config.json"

    with open(config_path, "r") as f:
        config = json.load(f)

    prompt = config["prompt"]
    model = config.get("model", "openai")
    temperature = float(config.get("temperature", "0.8"))
    system_message = config.get("system_message", "")
    out_dir = config.get("output_dir", "output")

    os.makedirs(out_dir, exist_ok=True)

    text = generate_text(prompt, model, temperature, system_message if system_message else None)

    timestamp = time.strftime("%Y%m%d_%H%M%S")
    md_path = os.path.join(out_dir, f"generated_{timestamp}.md")

    with open(md_path, "w", encoding="utf-8") as f:
        f.write(f"# Generated by AI Melli\n\n")
        f.write(f"| Key | Value |\n|-----|-------|\n")
        f.write(f"| **Model** | {model} |\n")
        f.write(f"| **Date** | {time.strftime('%Y-%m-%d %H:%M:%S')} |\n")
        f.write(f"| **Temperature** | {temperature} |\n")
        f.write(f"| **Prompt** | {prompt} |\n\n")
        f.write("---\n\n")
        f.write(text)

    # Save raw
    raw_path = os.path.join(out_dir, f"raw_{timestamp}.json")
    with open(raw_path, "w", encoding="utf-8") as f:
        f.write(text)

    chars = len(text)
    words = len(text.split())

    print(f"\n=== Text Generated ===")
    print(f"Characters: {chars}")
    print(f"Words: {words}")
    print(f"File: {md_path}")
    print(f"\n--- Preview (first 500 chars) ---")
    print(text[:500])
    if len(text) > 500:
        print("...")
    print("--- End Preview ---")

    result = {"file": md_path, "chars": chars, "words": words}
    with open("/tmp/ai_melli_result.json", "w") as f:
        json.dump(result, f)


if __name__ == "__main__":
    main()
